on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: AWS Lambda
    env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Replace Mongo Url
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'Variables.json'
      env:
        MONGO_URL: ${{secrets.MONGO_URL}}
    - name: Start Mongo Docker
      uses: isbang/compose-action@v1.3.2
      with:
        compose-file: "docker-compose.yml"
        down-flags: "--volumes"
        services: |
          mongodb
    - name: Run jest tests
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm i
    - run: npm run test
    - uses: actions/upload-artifact@v2  # upload test results
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: test-results
        path: junit.xml
    - run: npm i serverless
    - name: Deployment
      run: npm run deploy 
        
    
