on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Start Mongo Docker
      uses: isbang/compose-action@v1.3.2
      with:
        compose-file: "docker-compose.yml"
        down-flags: "--volumes"
        services: |
          mongodb
    - name: Run jest tests
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm i    
    - run: npm i --save-dev @types/jest
    - run: npm i --save-dev @types/node
    - run: npm run transpile
    - run: npm run test
